//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assembler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assembler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START
        ///RESET
        ///EQU
        ///EQUE
        ///ENTRY
        ///EXTRN
        ///END
        ///DAT
        ///ADC
        ///ADCE
        ///NOP.
        /// </summary>
        internal static string directives {
            get {
                return ResourceManager.GetString("directives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNTL 00
        ///HALT 000
        ///DUMP 001
        ///CLRD 010
        ///CLRT 011
        ///GOTO 100
        ///STACK 00
        ///PUSH 101
        ///POP 110
        ///TEST 111
        ///JUMP 01
        ///= 000
        ///^= 001
        ///&lt; 010
        ///&gt; 011
        ///&lt;= 100
        ///&gt;= 101
        ///TNULL 110
        ///DNULL 111
        ///SOPER 10
        ///ADD 000
        ///SUB 001
        ///MUL 010
        ///DIV 011
        ///OR 100
        ///AND 101
        ///READ 110
        ///WRITE 111
        ///MOPER 11
        ///ADD 000
        ///SUB 001
        ///MUL 010
        ///DIV 011
        ///OR 100
        ///AND 101
        ///READN 110
        ///READC 110
        ///WRITEN 111
        ///WRITEC 111.
        /// </summary>
        internal static string instructions {
            get {
                return ResourceManager.GetString("instructions", resourceCulture);
            }
        }
    }
}
