//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assembler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assembler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START
        ///RESET
        ///EQU
        ///EQUE
        ///ENTRY
        ///EXTRN
        ///END
        ///DAT
        ///ADC
        ///ADCE
        ///NOP.
        /// </summary>
        internal static string directives {
            get {
                return ResourceManager.GetString("directives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF.1 Invalid start directive.  Assembler has been stopped.
        ///EF.2 First line not a valid START.  First line must be a valid START.
        ///EF.3 LC is now larger than 1023.  Your program must use less than 1024 words of memory.
        ///EF.4 Exceeding the maximum number of symbols.  You must use 50 or less labels.
        ///ES.1 Invalid function code.  The function code entered is invalid.
        ///ES.2 Invalid Label defined, label ignored. Labels must start with A-Z, a-z and cannot be longer than 32 characters. 0-9 can be used after the first c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string errors {
            get {
                return ResourceManager.GetString("errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNTL HALT 00000
        ///CNTL DUMP 00001
        ///CNTL CLRD 00010
        ///CNTL CLRT 00011
        ///CNTL GOTO 00100
        ///STACK PUSH 00101
        ///STACK POP 00110
        ///STACK TEST 00111
        ///JUMP = 01000
        ///JUMP ^= 01001
        ///JUMP &lt; 01010
        ///JUMP &gt; 01011
        ///JUMP &lt;= 01100
        ///JUMP &gt;= 01101
        ///JUMP TNULL 01110
        ///JUMP DNULL 01111
        ///SOPER ADD 10000
        ///SOPER SUB 10001
        ///SOPER MUL 10010
        ///SOPER DIV 10011
        ///SOPER OR 10100
        ///SOPER AND 10101
        ///SOPER READN 10110
        ///SOPER READC 10110
        ///SOPER WRITEN 10111
        ///SOPER WRITEC 10111
        ///MOPER ADD 11000
        ///MOPER SUB 11001
        ///MOPER MUL 11010
        ///MOPER DIV 11011
        ///MOPER OR 11100
        ///MOPER AND 11101
        ///MOP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string instructions {
            get {
                return ResourceManager.GetString("instructions", resourceCulture);
            }
        }
    }
}
